structure_bilan_actif = [
    {"Code": "AD", "Intitulé": "IMMOBILISATIONS INCORPORELLES"},
    {"Code": "AE", "Intitulé": "Frais de développement et de prospection"},
    {"Code": "AF", "Intitulé": "Brevets, licences, logiciels et droits similaires"},
    {"Code": "AG", "Intitulé": "Fonds commercial et droit au bail"},
    {"Code": "AH", "Intitulé": "Autres immobilisations incorporelles"},
    {"Code": "AI", "Intitulé": "IMMOBILISATIONS CORPORELLES"},
    {"Code": "AJ", "Intitulé": "Terrains"},
    {"Code": "AK", "Intitulé": "Bâtiments"},
    {"Code": "AL", "Intitulé": "Aménagements, agencements et installations"},
    {"Code": "AM", "Intitulé": "Matériel, mobilier et actifs biologiques"},
    {"Code": "AN", "Intitulé": "Matériel de transport"},
    {"Code": "AP", "Intitulé": "AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS"},
    {"Code": "AQ", "Intitulé": "IMMOBILISATIONS FINANCIÈRES"},
    {"Code": "AR", "Intitulé": "Titres de participation"},
    {"Code": "AS", "Intitulé": "Autres immobilisations financières"},
    {"Code": "AZ", "Intitulé": "TOTAL ACTIF IMMOBILISÉ"},
    {"Code": "BA", "Intitulé": "ACTIF CIRCULANT HAO"},
    {"Code": "BB", "Intitulé": "STOCKS ET ENCOURS"},
    {"Code": "BG", "Intitulé": "CRÉANCES ET EMPLOIS ASSIMILÉS"},
    {"Code": "BH", "Intitulé": "Fournisseurs avances versées"},
    {"Code": "BI", "Intitulé": "Clients"},
    {"Code": "BJ", "Intitulé": "Autres créances"},
    {"Code": "BK", "Intitulé": "TOTAL ACTIF CIRCULANT"},
    {"Code": "BQ", "Intitulé": "Titres de placement"},
    {"Code": "BR", "Intitulé": "Valeurs à encaisser"},
    {"Code": "BS", "Intitulé": "Banques, chèques postaux, caisse et assimilés"},
    {"Code": "BT", "Intitulé": "TOTAL TRÉSORERIE-ACTIF"},
    {"Code": "BU", "Intitulé": "Écart de conversion-Actif"},
    {"Code": "BZ", "Intitulé": "TOTAL ACTIF"}
]