structure_bilan_passif = [
    {"Code": "CA", "Intitulé": "Capital"},
    {"Code": "CB", "Intitulé": "Apporteurs capital non appelé (-)"},
    {"Code": "CD", "Intitulé": "Primes liées au capital social"},
    {"Code": "CE", "Intitulé": "Écarts de réévaluation"},
    {"Code": "CF", "Intitulé": "Réserves indisponibles"},
    {"Code": "CG", "Intitulé": "Réserves libres"},
    {"Code": "CH", "Intitulé": "Report à nouveau (+ ou -)"},
    {"Code": "CJ", "Intitulé": "Résultat net de l'exercice (bénéfice + ou perte -)"},
    {"Code": "CL", "Intitulé": "Subventions d'investissement"},
    {"Code": "CM", "Intitulé": "Provisions réglementées"},
    {"Code": "CP", "Intitulé": "TOTAL CAPITAUX PROPRES ET RESSOURCES ASSIMILÉES"},
    {"Code": "DA", "Intitulé": "Emprunts et dettes financières diverses"},
    {"Code": "DB", "Intitulé": "Dettes de location-acquisition"},
    {"Code": "DC", "Intitulé": "Provisions pour risques et charges"},
    {"Code": "DD", "Intitulé": "TOTAL DETTES FINANCIÈRES ET RESSOURCES ASSIMILÉES"},
    {"Code": "DF", "Intitulé": "TOTAL RESSOURCES STABLES"},
    {"Code": "DH", "Intitulé": "Dettes circulantes HAO"},
    {"Code": "DI", "Intitulé": "Clients, avances reçues"},
    {"Code": "DJ", "Intitulé": "Fournisseurs d'exploitation"},
    {"Code": "DK", "Intitulé": "Dettes fiscales et sociales"},
    {"Code": "DM", "Intitulé": "Autres dettes"},
    {"Code": "DN", "Intitulé": "Provisions pour risques et charges à court terme"},
    {"Code": "DP", "Intitulé": "TOTAL PASSIF CIRCULANT"},
    {"Code": "DQ", "Intitulé": "Banques, crédits d'escompte"},
    {"Code": "DR", "Intitulé": "Banques, établissements financiers et crédits de trésorerie"},
    {"Code": "DT", "Intitulé": "TOTAL TRÉSORERIE-PASSIF"},
    {"Code": "DV", "Intitulé": "Écart de conversion-Passif"},
    {"Code": "DZ", "Intitulé": "TOTAL PASSIF"}
]